version: "2"
linters:
  enable:
    - importas
    - misspell
  settings:
    importas:
      alias:
        - pkg: go.temporal.io/sdk/(\w+)
          alias: temporalsdk_$1
        - pkg: go.temporal.io/api/(\w+)
          alias: temporalapi_$1
      no-unaliased: true
      no-extra-aliases: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - staticcheck
        path: bucket
        text: 'SA1019:'
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
